FROM python:3.9

RUN apt-get update -y
RUN apt-get install python3-pip build-essential -y
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt && chmod +x app.py
ENTRYPOINT ["python" , "app.py"] 

